###### Translations here #######

# SEO
title: "PapaKoala: Frühe Stimulationsübungen für Babys leicht gemacht"
tagline: Frühe Stimulationsübungen für Babys leicht gemacht
description: Frühe Stimulationsaktivitäten für Babys zur Förderung der Gehirnentwicklung, Bereitstellung früher sensorischer Erfahrungen und Aufbau eines Vertrauensgefühls.
# Seite Titel
page_title: "Pflege deines kleinen Genies: Entdecke PapaKoalas frühkindliche Stimulationsreise"
app_name: "PapaKoala: Neugeborenenentwicklung"
app_price: Abonnementbasiert
app_subtitle: Begreife eine Reise der Gehirnkapazität und des Bondings mit PapaKoala für Babys von 0 bis 1 Jahr.
app_description: "Die frühen Jahre sind eine Fenster der außergewöhnlichen Gelegenheit für die Entwicklung des Gehirns eines Babys. Dies ist die beste Zeit, um ihr intellektuelles Potenzial zu entfachen und die Grundlage für lebenslanges Lernen zu legen. \nPapaKoala, Ihr persönlicher Führer zur frühen Stimulation, befähigt Sie, die kognitive Entwicklung Ihres Kindes zu fördern und eine tiefe emotionale Verbindung zu ihm aufzubauen."

# Feature Liste
features:

- title: "Entfesseln Sie die Macht der frühen Stimulation"
  description: Tauchen Sie Ihr Baby in eine Welt stimulierender Erfahrungen ein, die ihre Gehirnentwicklung fördern und ihre Sinne wecken. PapaKoalas sorgfältig kuratierte Aktivitäten, die von Experten der Entwicklungsforschung geleitet werden, führen Ihr Kind in eine Symphonie von Bildern, Geräuschen und Berührungen ein, stimulieren ihre neuralen Bahnen und legen den Grundstein für zukünftigen Erfolg.
  fontawesome_icon_name: baby

- title: "Erleben Sie die Freude am interaktiven Lernen"
  description: Verabschieden Sie sich von monotonen Übungen und begrüßen Sie die unterhaltsame und lehrreiche Natur von PapaKoalas interaktiven Aktivitäten. Unsere videobasierten Tutorials bieten klare Anleitung und machen das Lernen für Eltern und Babys zu einem erfreulichen Erlebnis.
  fontawesome_icon_name: brain

- title: "Fördern Sie eine Bindung aus Liebe und Vertrauen"
  description: Frühe Stimulation geht über die kognitive Entwicklung hinaus. Es geht darum, eine sichere und liebevolle Bindung zwischen Ihnen und Ihrem Baby aufzubauen. PapaKoalas Aktivitäten legen Wert auf Berührung, die grundlegendste Form der Babyansprache, und fördern Vertrauen, Sicherheit und eine tiefe emotionale Verbindung.
  fontawesome_icon_name: heart


############## end of translations block #####





# App Info
ios_app_id                                : 1540490806                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                    # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").
spanish_page_link                         : https://es.papakoala.com                                                                                      
japan_page_link                           : https://jap.papakoala.com
english_page_link                         : https://papakoala.com  
chinese_page_link                         : https://cn.papakoala.com
german_page_link                          : https://ger.papakoala.com
southkorea_page_link                      : https://kor.papakoala.com
french_page_link                          : https://fr.papakoala.com
italian_page_link                         : https://it.papakoala.com
hindi_page_link                           : https://hi.papakoala.com
portuguese_page_link                      : https://pt.papakoala.com
brazil_page_link                          : https://ptbra.papakoala.com

app_icon                                  :                      # assets/appicon.png  Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.


enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : PapaKoala                                
your_link                                 : https://papakoala.com                     
your_city                                 :                              
email_address                             : hello@papakoala.com
facebook_username                         :                                           
instagram_username                        : papakoala_app
twitter_username                          : 
github_username                           : 
youtube_username                          : 




# Theme Settings
topbar_color                              : "#6EC8FF"
topbar_transparency                       : 0.4
topbar_title_color                        : "#444B54"

cover_image                               : assets/header_lowres.jpg                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.6

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#FFEAC1"

app_title_color                           : "#393e44"
app_price_color                           : "#FFFFFF"
app_description_color                     : "#ffffff"

app_language_color                        : "#FFEAC1"

feature_title_color                       : "#FFEAC1"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#FA6694"

social_icons_foreground_color             : "#BF82EC"
social_icons_background_color             : "#FFFFFF"

footer_text_color                         : "#000000"




# Google services
google_analytics: G-D89JL3TSP6




# url: papakoala.com




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

plugins:
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
